### ISSUE TITLE
缺少相关库

### ISSUE THREAD

**Issue by 929496959** [bbs-v2ex/v2ex#1]
app\nc\ArticleAdd.go:5:2: github.com/123456/c_code@v0.0.0-00010101000000-000000000000: replacement directory E:\codeing\go\c_code does not exist
app\nc\ArticleAdd.go:6:2: github.com/123456/c_code@v0.0.0-00010101000000-000000000000: replacement directory E:\codeing\go\c_code does not exist

**Comment by 929496959** [comment]
发错了

**Comment by bbs-v2ex** [comment]
https://github.com/bbs-v2ex/c_code
